### ISSUE TITLE
An annotation isn't supported

### ISSUE THREAD

**Issue by nicojs** [korthout/Cantis#12]
In my `glossary.txt` I get "No definitions found", while I expected one definition:

```java
/**
 * Represents an author
 */
@Target(value = {ElementType.METHOD, ElementType.TYPE})
@Retention(RetentionPolicy.RUNTIME)
@Repeatable(Authors.class)
@GlossaryTerm
public @interface Author {

    String value();

    int[] date() default {EMPTY_DATE};
}
```

I think annotations are not supported.

**Comment by korthout** [comment]
Good find! I don't think its an easy to fix issue, but it would be great if you could give it a try. I suspect that [JavaParser](https://github.com/javaparser/javaparser) does not see annotation declarations as class or interface declarations. In that case it has to do with this line:
https://github.com/korthout/Cantis/blob/537f8a88bb511b498bd64816576514167435ac89/src/main/java/com/github/korthout/cantis/Codebase.java#L90
